# Generated by Django 6.0.2 on 2026-02-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alert_frequency',
            field=models.CharField(choices=[('INSTANT', 'Real-time Alerts (Immediate)'), ('DAILY_DIGEST', 'Daily Summary (Sent at 8 PM)'), ('WEEKLY_SUMMARY', 'Weekly Digest (Every Sunday)')], default='DAILY_DIGEST', help_text='Frequency of price drop notifications', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Email verification status'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact number for SMS alerts', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
