# Generated by Django 6.0.2 on 2026-02-20 17:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('tx_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, help_text='Snapshot of balance post-transaction', max_digits=12)),
                ('category', models.CharField(choices=[('SIGNUP_BONUS', 'Signup Bonus'), ('PRICE_DROP_REWARD', 'Price Drop Reward'), ('PREMIUM_PURCHASE', 'Premium Purchase'), ('SYSTEM_ADJUSTMENT', 'System Adjustment')], default='SYSTEM_ADJUSTMENT', max_length=30)),
                ('idempotency_key', models.CharField(help_text='Prevents duplicate processing', max_length=255, unique=True)),
                ('security_hash', models.CharField(blank=True, help_text='SHA-256 HMAC for cryptographic integrity verification', max_length=256)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.wallet')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
