# Generated by Django 6.0.2 on 2026-02-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='data_signature',
            field=models.CharField(blank=True, help_text='HMAC-SHA256 Signature', max_length=64, null=True),
        ),
    ]
