# Generated by Django 6.0.2 on 2026-02-17 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_category_rename_brand_product_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='hash_verification',
            field=models.CharField(blank=True, help_text='Tamper-proof HMAC signature', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='is_significant_drop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='price_change_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='trend',
            field=models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN'), ('STABLE', 'STABLE')], default='STABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='scraper.category'),
        ),
    ]
