# Generated by Django 6.0.2 on 2026-02-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_pricehistory_hash_verification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='data_signature',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='hash_verification',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='price_change_percent',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='change_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Previously price_change_percent', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='integrity_hash',
            field=models.CharField(blank=True, help_text='SHA-256 integrity signature', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='scraper.tag'),
        ),
    ]
