# Generated by Django 6.0.2 on 2026-02-17 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_alter_pricealert_uuid_alter_product_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Traceability ID', unique=True)),
                ('price_at_alert', models.DecimalField(blank=True, decimal_places=2, help_text='Price at the exact moment of alert', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('SUPPRESSED', 'SUPPRESSED')], db_index=True, default='PENDING', max_length=20)),
                ('alert_type', models.CharField(choices=[('Drop', 'Price Drop'), ('Restock', 'Back in Stock'), ('System', 'System Alert')], default='Drop', max_length=20)),
                ('intent_timestamp', models.DateTimeField(auto_now_add=True, help_text='Exact millisecond system decided to alert')),
                ('smtp_response_code', models.CharField(blank=True, help_text='e.g. 250 OK, 550 Rejected', max_length=10, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Raw SMTP traceback', null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='scraper.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Audit Trail',
                'ordering': ['-intent_timestamp'],
            },
        ),
    ]
