# Generated by Django 6.0.2 on 2026-02-21 04:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='alert_priority',
            field=models.CharField(choices=[('LOW', 'Low - Standard Queue'), ('HIGH', 'High - Fast Track'), ('VIP', 'VIP - Real Time')], default='LOW', help_text='Determined by Wallet Ecosystem mapping', max_length=10),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Scalability Hook: Storage for anomaly detection flags'),
        ),
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extensible JSON for Signals (e.g., is_anomalous fraud detection)'),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=models.TextField(blank=True, help_text='NLP Vector Placeholder for Semantic Matchmaker', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='trend_indicator',
            field=models.CharField(default='STABLE', help_text='Schema Hook for LSTM Integration', max_length=20),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='is_reward_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='last_notified_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='potential_reward',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='reward_points_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='intent_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='price_at_alert',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='smtp_response_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='change_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
